@startuml
class com.example.georgepromax.navigation {
- ImageButton arrangeGameBtn
- ImageButton fourInLineBtn
- PlayerModel playerModel
# void onCreate(Bundle)
+ void init()
+ void onClick(View)
}

class com.example.georgepromax.PlayerModel {
~ String userName
~ String password
~ String email
~ String phoneNumber
~ String gameTimeBest
+ String getGameTimeBest()
+ void setGameTimeBest(String)
+ String getUserName()
+ void setUserName(String)
+ String getPassword()
+ void setPassword(String)
+ String getEmail()
+ void setEmail(String)
+ String getPhoneNumber()
+ void setPhoneNumber(String)
}

class com.example.georgepromax.fourInAline {
- TextView txtFourTitle
- ImageView[] btn
- int turns
- ImageView[][] grid
- int[][] gridMone
# void onCreate(Bundle)
+ void init()
- void fvbid()
+ void onClick(View)
- void checkWinner()
- void winMessage(int)
}
class com.example.georgepromax.game {
- TextView GameTitle
- TextView CountDown
- Button[] btnArr
- Button btnBest
- Button saveChanges
- Utility utility
- ImageButton help
- ImageButton undo
- int[] arr
- Stack<Integer> stackUndo
- String thePlayer
- String gameTimeBest
- PlayerModel playerModel
- Button btnLeaderboard
- String[] dbName
- int index
- String temporary
- CountDownTimer countDownTimer
- int counter
- long maxTime
- boolean isRunning
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
- void resetCounter()
# void onCreate(Bundle)
- void myTimer()
- void init()
+ void onClick(View)
- void save()
+ void emptyMyStack()
+ boolean checkSolvable(int[])
- void buttonColor44()
- void buttonColor24()
- void buttonColor33()
- void setGameGrid(int)
- void play(View)
}

class com.example.georgepromax.gameTimeLeaderboard {
- ListView listView
- String[] dbName
- String dbTime
~ int index
- LeaderboardItem leaderboardItem
- ArrayList<LeaderboardItem> list
- MyAdapter myAdapter
# void onCreate(Bundle)
- void init()
- void makeMyList()
+ int minIndexArr(int[])
+ void sortUp()
}

class com.example.georgepromax.LeaderboardItem {
- String name
- String time
- int imgItem
+ String getName()
+ String getTime()
+ int getImgItem()
+ void setName(String)
+ void setTime(String)
+ void setImgItem(int)
}

class com.example.georgepromax.alarmSet {
- TextView timetxt
- Button selectTimeBtn
- Button setAlarmBtn
- Button cancelAlarmBtn
- MaterialTimePicker picker
- Calendar calendar
- AlarmManager alarmManager
- PendingIntent pendingIntent
# void onCreate(Bundle)
+ void init()
- void createNotificationChannel()
+ void onClick(View)
- void cancelAlarm()
- void setAlarm()
- void showTimePicker()
}
class com.example.georgepromax.AlarmReceiver {
+ void onReceive(Context,Intent)
}
class com.example.georgepromax.MainActivity {
- TextView txtTitle
- boolean checkMusic
- Button play
- int index
- PlayerModel playerModel
- String thePlayer
- String gameTimeBest
- String[] dbName
- String[] dbPass
- EditText txtUser
- TextView txtValidUser
- EditText txtPassword
- TextView txtValidPassword
- Button btnSend
- Button btnRegister
- CheckBox checkUser
- ImageView imgLog
- ImageView imgHello00
- ImageView imgHello01
- ImageView imgHello02
- Random random
- ImageButton imgBtnEye01
- ImageButton imgBtnEye02
- Validators valid
- String[] welcome
- int[] randomArr
- int r
# void onCreate(Bundle)
# void onDestroy()
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
- void init()
+ void onClick(View)
}

class com.example.georgepromax.Utility {
+ int index
+ int temp
+ int[] randomArr(int,int)
}

class com.example.georgepromax.RegistrationPage {
- TextView txtTitleR
- EditText txtUserR
- TextView txtValidUserR
- EditText txtPasswordR
- TextView txtValidPasswordR
- EditText txtEmailR
- TextView txtValidEmailR
- EditText txtPhoneR
- TextView txtValidPhoneR
- Button btnSendR
- Validators valid
- String[] dbName
# void onCreate(Bundle)
+ void init()
+ void onClick(View)
}
class com.example.georgepromax.Validators {
- Context context
+ String checkUserName(String)
+ String checkPassword(String)
+ String checkEmail(String)
+ String checkPhone(String)
}

class com.example.georgepromax.MusicService {
- MediaPlayer mediaPlayer
+ IBinder onBind(Intent)
+ void onCreate()
+ int onStartCommand(Intent, int, int)
+ void onDestroy()
}

class com.example.georgepromax.MyAdapter {
- Context context
- List<LeaderboardItem> object
+ View getView(int, View, ViewGroup)
}


android.widget.ArrayAdapter <|-- com.example.georgepromax.MyAdapter
android.app.Service <|-- com.example.georgepromax.MusicService
androidx.appcompat.app.AppCompatActivity <|-- com.example.georgepromax.gameTimeLeaderboard
com.example.georgepromax.OnClickListener <|.. com.example.georgepromax.navigation
androidx.appcompat.app.AppCompatActivity <|-- com.example.georgepromax.navigation
com.example.georgepromax.OnClickListener <|.. com.example.georgepromax.fourInAline
androidx.appcompat.app.AppCompatActivity <|-- com.example.georgepromax.fourInAline
com.example.georgepromax.OnClickListener <|.. com.example.georgepromax.game
androidx.appcompat.app.AppCompatActivity <|-- com.example.georgepromax.game
com.example.georgepromax.OnClickListener <|.. com.example.georgepromax.alarmSet
androidx.appcompat.app.AppCompatActivity <|-- com.example.georgepromax.alarmSet
android.content.BroadcastReceiver <|-- com.example.georgepromax.AlarmReceiver
com.example.georgepromax.OnClickListener <|.. com.example.georgepromax.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.georgepromax.MainActivity
android.view.View.OnClickListener <|.. com.example.georgepromax.RegistrationPage
androidx.appcompat.app.AppCompatActivity <|-- com.example.georgepromax.RegistrationPage
com.example.georgepromax.Utility <|-- com.example.georgepromax.Validators
@enduml